<a href="https://colab.research.google.com/github/AlexErmakov77/ML-Python/blob/main/2_1_Numpy_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Занятие 1

## Numpy

### Вспомним какие у нас есть контейнеры в Python
Основными контейнерами (структурами, которые могут содержать в себе другие данные или другие структуры) в python ялвяются
1. множество (set)
2. кортеж (tuple)
3. словари (dict)
4. списки (list)

Рассмотрим на примере списка возможности таких кортежей

Мы можем создавать объекты типа list вот таким образом:

In [ ]:
a = [1, 2, 3]
a

[1, 2, 3]

И можем добавлять произвольные элементы в список вот так

In [ ]:
a.append(1)
a

[1, 2, 3, 1]

При этом нам доступна индексация с 0, мы можем получить произвольный элемент списка по его индексу

In [ ]:
a[0]

In [ ]:
a[1]

Кроме того, доступна индексация "с конца", нужно просто передавать отрицательные индексы

In [ ]:
a[-1]

list в python позволяет нам хранить в нем произвольные объекты: целые числа, строки, другие контейнеры. Причем это можно делать одновременно

In [ ]:
b = ['1', 2.0, 4, ['a', 'b', 'c']]
b

['1', 2.0, 4, ['a', 'b', 'c']]

In [ ]:
b[3]

['a', 'b', 'c']

### Что же нам дает Numpy?

Сначала импортируем библиотеку привычным нам образом. np это псевдоним, и он позволяет нам делать вызовы функций из библиотеки более коротким способом

In [ ]:
import numpy as np
# numpy.add -> np.add

Мы можем проверить тип данных на который ссылается наша переменная с помощью встроенного метода type.

Например, мы видим, что тип объекта на который ссылается переменная a ожидаемо list

In [ ]:
type(a)

list

#### Numpy array (np.ndarray, numpy массив, массив numpy)
Это набор значений **одного и того же типа**, который индексируется набором неотрицательных целых чисел. Количество измерений - это ранг массива; форма (shape) массива представляет собой набор целых чисел, дающий размер массива по каждому измерению.

Мы можем инициализировать пустые массивы из вложенных списков Python и обращаться к элементам с помощью квадратных скобок

In [ ]:
data = np.array([1.0,2,3,4,5,6,7])

In [ ]:
type(data)

numpy.ndarray

Мы также можем проверить какого типа значения храняться в нашем numpy массиве

In [ ]:
data.dtype 

dtype('float64')

По умолчанию numpy будет присваивать наиболее вместительный полходящий тип данных. Например, выше это тип integer из 64 бит. Это означает, что на каждый элемент нашего списка будет выделено **четко** 64 бита. 

Вы можете подробнее прочитать про представление чисел в памяти компьютера здесь:
1. [Целое](https://ru.wikipedia.org/wiki/%D0%A6%D0%B5%D0%BB%D0%BE%D0%B5_(%D1%82%D0%B8%D0%BF_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85))
2. [Число с плавающей точкой](https://ru.wikipedia.org/wiki/%D0%A7%D0%B8%D1%81%D0%BB%D0%BE_%D1%81_%D0%BF%D0%BB%D0%B0%D0%B2%D0%B0%D1%8E%D1%89%D0%B5%D0%B9_%D0%B7%D0%B0%D0%BF%D1%8F%D1%82%D0%BE%D0%B9)

На самом деле, зная в каком диапазоне будут находиться наши элементы numpy массива, мы можем явно указать тип данных поменьше, например, целое число из 32 бит. За счет этого мы можем существенно экономить требуемые для вычисления ресурсы.

[Доступные типы данных в numpy](https://pyprog.pro/data_types.html#:~:text=%D0%92%20NumPy%20%D1%81%D1%83%D1%89%D0%B5%D1%81%D1%82%D0%B2%D1%83%D0%B5%D1%82%205%20%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D1%8B%D1%85,%D0%BA%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81%D0%BD%D1%8B%D0%B5%20%D1%87%D0%B8%D1%81%D0%BB%D0%B0%20(%D1%82%D0%B8%D0%BF%20complex).)

In [ ]:
data = np.array([1,2,3])
data.dtype

dtype('int64')

##### Типы данных
Numpy предоставляет большой набор числовых типов данных, которые вы можете использовать для создания массивов. Numpy пытается угадать тип данных при создании массива, но функции, которые создают массивы, обычно также включают необязательный аргумент для явного указания типа данных.

In [ ]:
# dtype
np.int
np.int32
np.int8
np.int16
np.float16
np.float32
np.datetime
np.bool # бинарный тип данных, который хранит True или False

Как можно перейти от одного типа данных к другому?

In [ ]:
a = np.array(['1', '2', '3'])
a.dtype

dtype('<U1')

In [ ]:
a = np.array(['msc', 'ivan', 'artem'])

In [ ]:
a

array(['msc', 'ivan', 'artem'], dtype='<U5')

In [ ]:
a.astype(np.int32)

array([1, 2, 3], dtype=int32)

Следующий код вызывает ошибку, так как интерпретатор python не может преобразовать строчку '2dsad' к целому числу.

In [ ]:
a = np.array(['1', '2dsad', '3'])
a.astype(np.int32)

ValueError: ignored

In [ ]:
np.array([True, False, False]).astype(np.int32)

array([1, 0, 0], dtype=int32)

Общее напоминание о конверсии типов данных в логический тип (True или False)

In [ ]:
bool(10)

True

In [ ]:
bool(1)

True

In [ ]:
bool(-0.0001)

True

In [ ]:
bool(0)

False

In [ ]:
bool([2])

True

In [ ]:
bool([])

False

In [ ]:
l = []
if not l:
  print("l is empty")

l is empty


Мы можем также посмотреть размерность списка (т.е кол-во элементов в нем)

In [ ]:
data

array([1, 2, 3])

In [ ]:
data.shape

(3,)

In [ ]:
data

array([1, 2, 3])

Существенным отличием от списков в python является невозможность добавления новых элементов в numpy массив. Подразумевается, что размерность фиксирована, а новые numpy массивы получаются преобразованиями (функциями) над исходными списками, матрицами или тензорами (матрицами размерности больше 2). 

In [ ]:
data.append(1) # мы просто так не можем изменять размерность текущего объектв

AttributeError: ignored

Простая индексация при этом сохраняется

In [ ]:
data[1]

2

In [ ]:
data[-1]

3

Также просто мы можем получить двумерный массив (или матрицу)

In [ ]:
ARRAY_DTYPE = np.int16
data = np.array([[1,2,3], [1,1,1]], dtype=ARRAY_DTYPE)
data

array([[1, 2, 3],
       [1, 1, 1]], dtype=int16)

In [ ]:
data.shape

(2, 3)

In [ ]:
np.array([1.0, 2.0, 3.0]).dtype # есть также диапазоны поменьше np.float16, np.float32, 

dtype('float64')

Кстати, есть и специальные типы данных, например, для даты. Это позволяет работать с ними именно как с датами, а не строками. Например, находить разницу между двумя списками дат в днях.

In [ ]:
np.array(['2020-08-24', '2020-08-23'], dtype=np.datetime64)

array(['2020-08-24', '2020-08-23'], dtype='datetime64[D]')

In [ ]:
np.array(['2020-08-24', '2020-08-23'], dtype=np.datetime64) - np.array(['2020-08-22', '2020-08-20'], dtype=np.datetime64)

array([2, 3], dtype='timedelta64[D]')

Есть несколько функций для создания массивов

Массив из нулей произвольной размерности

In [ ]:
np.zeros((4,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Или из единиц

In [ ]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
x = [1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape

(5,)

Или из произвольных чисел

In [ ]:
np.full((10,10), 7)

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

Можем сделать так называемую единичную матрицу произвольного размера

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Или массив произвольного размера из случайных значений от 0 до 1

In [ ]:
np.random.rand(10)

array([0.84817126, 0.91372748, 0.24807533, 0.09615925, 0.57227858,
       0.16718968, 0.11908277, 0.1776814 , 0.14311123, 0.77325611])

In [ ]:
np.random.rand(100, 100)

array([[0.44813759, 0.02686846, 0.1891166 , ..., 0.69944742, 0.38235124,
        0.83216103],
       [0.4408114 , 0.08779399, 0.23674123, ..., 0.53311862, 0.57346796,
        0.62211884],
       [0.15292436, 0.79487056, 0.43584725, ..., 0.75585985, 0.28213187,
        0.31756623],
       ...,
       [0.83455115, 0.65867832, 0.79005538, ..., 0.77950152, 0.74224664,
        0.28924128],
       [0.39883606, 0.16675219, 0.68388658, ..., 0.86799017, 0.81470137,
        0.58392237],
       [0.36263609, 0.21302298, 0.18279421, ..., 0.88276964, 0.2309405 ,
        0.24980261]])

In [ ]:
np.random.rand(10,5,3).shape

(10, 5, 3)

**Зафиксируем**

Итак, в numpy массивах у всех элементов одинаковый тип данных, а также мы не можем произвольно менять его размерность. Забегая немного вперед, за счет этого некоторые операции мы можем производить быстрее. Тут python приобретает некоторые плюсы языков со статической типезацией типа C. Помимо этого, стоит отметить, что библиотека pandas и многие библиотеки машинного обучения используют примитивы из библиотеки numpy.

#### Индексация
Numpy предлагает несколько способов индексации массивов.
Slicing: Как и в списках Python, массивы могут быть "нарезаны". Поскольку массивы могут быть многомерными, нужно указать срез для каждого измерения массива.

Общий синтаксис для произвольного кол-ва размерностей для слайсинга: `[от:до:шаг, от:до:шаг, ...]`. **от** включительно, а **до** не включительно

При этом, если по одной из размерностей нужны все индексы, то необязательно знать начало и конец, можно просто опустить значения от и до, чтобы получилось что-то вроде

`[:,:,1:5]` берем все индексы по размерностям 0 и 1, а в последней берем индексы от 1 включительно и до 5 не включительно.

Также, изучите примеры ниже

In [ ]:
# в одномерном варианте есть и для обычных списков
[1,2,3,4,5][1:4]

[2, 3, 4]

In [ ]:
[1,2,3,4,5][1:4:2] # общий синтаксис такой: [от:до:с каким шагом]

[2, 4]

In [ ]:
range(2,10,2)

range(2, 10, 2)

In [ ]:
list(range(2,10,2))

[2, 4, 6, 8]

`np.arange(0,100)` возвращает numpy массив из 100 элементов от 0 до 99 включительно

In [ ]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(0,100)[5:50:3] # взять значения от 5 индекса включительно до 50-ого невключительно с шагом 3

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Создадим произвольную матрицу размера 3 на 4, где значения будем брать из [равномерного распределения](https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BF%D1%80%D0%B5%D1%80%D1%8B%D0%B2%D0%BD%D0%BE%D0%B5_%D1%80%D0%B0%D0%B2%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%BD%D0%BE%D0%B5_%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5) на отрезке от 10 до 100

In [ ]:
test_matrix = np.random.uniform(10, 100, (3,4))
test_matrix

array([[91.34568145, 12.59967839, 91.24194595, 47.33783237],
       [15.81495856, 22.2706761 , 40.79611275, 94.06726775],
       [98.48301437, 49.15638272, 21.37162287, 38.09000217]])

In [ ]:
a = np.array([1, 2, 3, 4])

[[1, 2],
 [3, 4]]

[[1, 2], [3, 4]]

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.reshape((2,2))

array([[1, 2],
       [3, 4]])

`.reshape` позволяет поменять размерность матрицы. Главное правило здесь, чтобы произведение старых размерностей было равно произведению новых. 

Например, (100,) -> (20,5) ок, так как 100 = 20 * 5

или

(10,2,3) -> (15,4) ок, так как 10 \* 2 \* 3 = 15 * 4

но

(10,2,3) -> (15,2,3) не ок, так как 10 \* 2 \* 3 != 15 * 2 * 3

In [ ]:
a = np.arange(1,101)

In [ ]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
a.reshape((20,5))

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [ ]:
arr = np.arange(60)
print(arr.shape)
arr = arr.reshape((10,2,3))
arr

(60,)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41]],

       [[42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53]],

       [[54, 55, 56],
        [57, 58, 59]]])

In [ ]:
arr.reshape((15,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [ ]:
arr.reshape((15,2,3))

ValueError: ignored

In [ ]:
sample_matrix = np.arange(1,101).reshape(20,5)
sample_matrix

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

Рассмотрим также некоторые упражнения
1. выбрать каждую вторую строчку из матрицы, начиная с самой первой
2. выбрать каждый второй столбец, начиная с самого первого
3. выбрать подматрицу обозначенную числами 53 и 75

In [ ]:
# выберем строку
sample_matrix[3]

array([16, 17, 18, 19, 20])

In [ ]:
sample_matrix[:, 3]

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])

In [ ]:
# 1. выбрать каждую вторую строчку из матрицы, начиная с самой первой
sample_matrix[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55],
       [61, 62, 63, 64, 65],
       [71, 72, 73, 74, 75],
       [81, 82, 83, 84, 85],
       [91, 92, 93, 94, 95]])

In [ ]:
sample_matrix

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [ ]:
# 2. выбрать каждый второй столбец, начиная с самого первого
sample_matrix[:, ::2]

array([[  1,   3,   5],
       [  6,   8,  10],
       [ 11,  13,  15],
       [ 16,  18,  20],
       [ 21,  23,  25],
       [ 26,  28,  30],
       [ 31,  33,  35],
       [ 36,  38,  40],
       [ 41,  43,  45],
       [ 46,  48,  50],
       [ 51,  53,  55],
       [ 56,  58,  60],
       [ 61,  63,  65],
       [ 66,  68,  70],
       [ 71,  73,  75],
       [ 76,  78,  80],
       [ 81,  83,  85],
       [ 86,  88,  90],
       [ 91,  93,  95],
       [ 96,  98, 100]])

In [ ]:
# 3. выбрать подматрицу обозначенную числами 53 и 75
print(sample_matrix)
sample_matrix[10:15:, 2:]

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]


array([[53, 54, 55],
       [58, 59, 60],
       [63, 64, 65],
       [68, 69, 70],
       [73, 74, 75]])

In [ ]:
sample_matrix = np.arange(30).reshape((6,5))

In [ ]:
sample_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
sample_matrix[3, 4]

19

In [ ]:
sample_matrix[15, 18]

IndexError: ignored

In [ ]:
sample_matrix[3:15:, 3:]

array([[18, 19],
       [23, 24],
       [28, 29]])

В numpy доступна фильтрация значений в массиве по маске. Маска это numpy массив той же формы, что и исходный, состоящий только из булевых значений True (истина) или False (ложь)

In [ ]:
sample_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
sample_matrix > 10 # маска. False там где <= 10, True где больше 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

Мы можем просто передать эту маску внутрь квадратных скобок, и получить отфильтрованный набор данных

In [ ]:
sample_matrix[sample_matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [ ]:
sample_matrix == 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
sample_matrix[sample_matrix == 10]

array([10])

Также, поскольку маски это всего навсего numpy массивы из элементов типа np.bool, мы можем создавать логические связки из масок. Например, с помощью логического И (&), логического ИЛИ (||). Также представлены специальные методы ([см. раздел 7.6.2](https://pyprog.pro/basic_operations.html))

In [ ]:
(sample_matrix > 10) & (sample_matrix <= 20)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
sample_matrix[(sample_matrix > 10) & (sample_matrix <= 20)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### Операции с numpy массивами
Основные математические функции работают поэлементно на массивах и доступны как в виде перегрузок операторов, так и в виде функций в модуле Numpy.

In [ ]:
a = np.array([1,2,3])
print(a)
b = np.ones(3)
print(b)

[1 2 3]
[1. 1. 1.]


Поэлементная сумма и разность

In [ ]:
a + b

array([2., 3., 4.])

In [ ]:
a - b

array([0., 1., 2.])

In [ ]:
c = np.full((3,2), 5)
c

array([[5, 5],
       [5, 5],
       [5, 5]])

In [ ]:
a - c # выведет ошибку о несовпадении размерностей.
# Если нам нужна какая-то поэлементная операция типа сложения, умножения, разности, деления, то
# в первом приближении размерности должны совпадать либо быть broadcastable (см. дальше)

ValueError: ignored

Поэлементное умножение

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([1., 1., 1.])

In [ ]:
a * b

array([1., 2., 3.])

Поэлементное деление

In [ ]:
b / a

array([1.        , 0.5       , 0.33333333])

Скалярное произведение для одномерных массивов

In [ ]:
# 1 2 3 
# 1 1 1

# 1*1 + 2*1 + 3*1

In [ ]:
# 1 1
# 2 1
# 3 1

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a.shape

(5,)

In [ ]:
a.reshape((1, 5))

array([[1, 2, 3, 4, 5]])

In [ ]:
a.reshape((1, 5)).shape

(1, 5)

In [ ]:
a.reshape((5, 1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
a.reshape((5, 1)).shape

(5, 1)

In [ ]:
a = np.array([1,2,3]).reshape((3,1))
print(a)
print()
b = np.array([1,1,1]).reshape((1,3))
print(b)

[[1]
 [2]
 [3]]

[[1 1 1]]


In [ ]:
a.shape

(3, 1)

In [ ]:
b.shape

(1, 3)

In [ ]:
a @ b 

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
a @ b 

6.0

Матричное умножение для матриц

In [ ]:
b = np.ones(3)
print(b)

[1. 1. 1.]


In [ ]:
m = np.full((5,3), 3)
m

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
m

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
m @ b

array([9., 9., 9., 9., 9.])

Numpy предоставляет много полезных функций для выполнения вычислений на массивах.

Полный список можно найти [здесь](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [ ]:
# sum, mean etc

In [ ]:
m

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
np.sum(m)

45

In [ ]:
sample_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
np.mean(sample_matrix)

14.5

[Материал по осям в pandas (в numpy аналогично) ](https://railsware.com/blog/python-for-machine-learning-pandas-axis-explained/#:~:text=A%20DataFrame%20object%20has%20two,it%20goes%20along%20rows%20direction.)

![axes](https://railsware.com/blog/wp-content/uploads/2018/11/data-frame-axes.png)

![axes](https://i.stack.imgur.com/FzimB.png)

In [ ]:
sample_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
np.sum(sample_matrix, axis=0) # сумма по каждому столбцу

array([75, 81, 87, 93, 99])

In [ ]:
np.sum(sample_matrix, axis=1) # сумма по строкам

array([ 10,  35,  60,  85, 110, 135])

In [ ]:
print(sample_matrix.shape)
np.sum(sample_matrix, axis=0)

(6, 5)


array([75, 81, 87, 93, 99])

In [ ]:
np.sum(sample_matrix, axis=0)

array([75, 81, 87, 93, 99])

In [ ]:
sample_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
np.sum(sample_matrix, axis=1) # сумма по каждой строке

array([ 10,  35,  60,  85, 110, 135])

In [ ]:
print(sample_matrix.shape)
np.sum(sample_matrix, axis=1)#.shape

(6, 5)


array([ 10,  35,  60,  85, 110, 135])

In [ ]:
arr = np.arange(30).reshape(2, 5, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [ ]:
np.sum(arr, axis=2)

array([[ 3, 12, 21, 30, 39],
       [48, 57, 66, 75, 84]])

In [ ]:
np.sum(arr, axis=1)

array([[ 30,  35,  40],
       [105, 110, 115]])

In [ ]:
np.sum(arr, axis=0)

array([[15, 17, 19],
       [21, 23, 25],
       [27, 29, 31],
       [33, 35, 37],
       [39, 41, 43]])

Помимо вычисления математических функций с использованием массивов, нам часто необходимо изменять или иным образом манипулировать данными в массивах. 

[Глоссарий функций](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html) для манипуляций с массивами

[Транспонирование матрицы](https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0) 

In [ ]:
sample_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
sample_matrix.shape

(6, 5)

In [ ]:
sample_matrix.T

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [ ]:
print(sample_matrix.T.shape)

(5, 6)


Соединение нескольких массивов `np.concatenate`.

axis = 0 соответствует соединению "по вертикали"

axis = 1 соответствует соединению "по горизонтали"

Также см. изображение выше, чтобы было проще запомнить

In [ ]:
sample_matrix = np.arange(12).reshape((4,3))
sample_matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
[sample_matrix, sample_matrix]

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])]

In [ ]:
np.concatenate([sample_matrix, sample_matrix], axis=1)

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11]])

In [ ]:
np.concatenate([sample_matrix, sample_matrix], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.vstack([sample_matrix, sample_matrix]).shape # аналог concatenate с axis=0

(8, 3)

In [ ]:
np.vstack([sample_matrix, sample_matrix])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate([sample_matrix, sample_matrix], axis=1).shape

(4, 6)

In [ ]:
np.concatenate([sample_matrix, sample_matrix], axis=1)

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11]])

In [ ]:
np.hstack([sample_matrix, sample_matrix]).shape # аналог concatenate с axis=1

(4, 6)

In [ ]:
np.hstack([sample_matrix, sample_matrix])

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11]])

In [ ]:
sample_matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
sample_matrix.shape

(4, 3)

In [ ]:
eye = np.round(np.random.rand(2,4), 2)

In [ ]:
eye

array([[0.86, 0.36, 0.79, 0.42],
       [0.32, 0.97, 0.65, 0.94]])

In [ ]:
eye.shape

(2, 4)

In [ ]:
eye.T

array([[0.86, 0.32],
       [0.36, 0.97],
       [0.79, 0.65],
       [0.42, 0.94]])

In [ ]:
eye.T.shape

(4, 2)

In [ ]:
np.hstack([sample_matrix, eye])

array([[ 0.  ,  1.  ,  2.  ,  0.13,  0.54],
       [ 3.  ,  4.  ,  5.  ,  0.81,  0.61],
       [ 6.  ,  7.  ,  8.  ,  0.59,  0.68],
       [ 9.  , 10.  , 11.  ,  0.93,  0.43]])

In [ ]:
np.hstack([eye, sample_matrix])

array([[ 0.13,  0.54,  0.  ,  1.  ,  2.  ],
       [ 0.81,  0.61,  3.  ,  4.  ,  5.  ],
       [ 0.59,  0.68,  6.  ,  7.  ,  8.  ],
       [ 0.93,  0.43,  9.  , 10.  , 11.  ]])

In [ ]:
np.vstack([eye, sample_matrix])

ValueError: ignored

Мы можем быстро привести многомерный массив к одномерному

In [ ]:
print(sample_matrix.shape) # (20,5)
print(np.ravel(sample_matrix).shape) # (100,)

(4, 3)
(12,)


In [ ]:
sample_matrix.reshape(12,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a = np.ones((4,5,6))
a.shape

(4, 5, 6)

In [ ]:
a

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [ ]:
a.flatten() # результат идентичный ravel

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

**Текст, выделенный полужирным шрифтом**
#### Broadcasting (Расширение/адаптация размерностей)
Мощный механизм, позволяющий NumPy работать с массивами различной формы при выполнении арифметических операций. Часто у нас есть меньший массив и больший массив, и мы хотим использовать меньший массив несколько раз, чтобы выполнить некоторую операцию над большим массивом

In [ ]:
# прибавление вектора ко всем строкам матрицы

In [ ]:
# без broadcasting
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([3,4,5])
# empty like создает пустую матрицу такого же размера как x
y = np.empty_like(x) # создаем пустую структуру, в нее мы будем складывать ответ
print(y.shape)

print(x)
print()
print(v)
print()

for i in range(4):
  y[i, :] = x[i, :] + v

print(y)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[3 4 5]

[[ 4  6  8]
 [ 7  9 11]
 [10 12 14]
 [13 15 17]]


`np.tile` повторяет массив v (n,m,...) n раз по 0-ой оси и m раз по 1-ой итд, получается новый массив

In [ ]:
v

array([3, 4, 5])

In [ ]:
vv = np.tile(v, (4,1))
vv # получилась матрица такой же размерности как и матрица x

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [ ]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
y = x + vv
print(y)

[[ 4  6  8]
 [ 7  9 11]
 [10 12 14]
 [13 15 17]]


In [ ]:
x + v

array([[ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14],
       [13, 15, 17]])

Бродкастинг двух массивов работает следующим образом:
*   Если массивы не имеют одинаковый ранг (кол-во размерностей), нужно выровнять кол-во размерностей, добавлением дополнительных "единичных" размерностей массиву меньшего ранга
*   Говорят, что два массива *совместимы* в i-ой размерности, если они имеют одинаковый по величине набор значений в этой размерности, или если один из массивов имеет ровно 1 элемент в этом измерении.
*   Массивы **broadcastable**, если они совместимы во всех размерностях.
*   После адаптации каждый массив ведет себя так, как будто он имеет форму, равную поэлементному максимуму форм двух входных массивов.
*   В любом измерении, где один массив имел размер 1, а другой массив имел размер больше 1, первый массив ведет себя так, как если бы он был скопирован "вдоль" этого измерения

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print()
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]]


In [ ]:
a + b

ValueError: ignored

Прибавим теперь не по строкам, а по столбцам

In [ ]:
v

array([3, 4, 5])

Для этого нужно добавить "дополнительную" размерность 1.

Обратите внимание, что (4,) и (4,1) это разные numpy массивы по форме. Первое интерпретируется как строка матрицы, а второе как столбец. Проведите над этим утверждением пару минут.

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
[1,2,3,4] # список

[1, 2, 3, 4]

In [ ]:
{'one' : 1,
 'two' : 2
 } # словарь

{'one': 1, 'two': 2}

In [ ]:
print({1,2,2,4}) # множество
set([1,2, 2,3])

{1, 2, 4}


{1, 2, 3}

In [ ]:
[1,2,3,4][2]

3

In [ ]:
np.arange(1,5)[2]

3

In [ ]:
np.arange(1,5).reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
x + np.arange(1,5).reshape(4,1) # у нас происходит сложение по столбцам

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])